### ISSUE TITLE
想要低调使用

### ISSUE THREAD

**Issue by insomnia417** [xylplm/media-saber-wiki#20]
insomnia417@qq.com

**Comment by insomnia417** [comment]
求入群

**Comment by xylplm** [comment]
ms处于低调的使用，不接受公众使用。要加入，需要展示一技之长。优先懂技术有责任感的pter，会python、会go、会vue、会flutter、会swift的、会写NT规则、会基本的Html+CSS，会站点适配的满足其中一项都可以。如果是妹子，请忽略以上条件，直接通过
